### ISSUE TITLE
Visualizer freezing

### ISSUE THREAD

**Issue by AsafJosefMor** [daveagp/java_jail#8]
Hi Dave, amazing work on the visualizer!

My problem is that after installation on Ubuntu server (Vbox) and connecting through browser on host the Visualizer freezes after clicking "Visualize Execution".

Can you help?

![image](https://cloud.githubusercontent.com/assets/20573715/23268600/ed6a73f6-f9f6-11e6-869a-e75063161536.png)

**Comment by daveagp** [comment]
I don't know if I can provide full assistance as there's not much info to go on, but I could give you an idea of what to look for. What is the http response? Look at the network activity in the chrome developer tools.

**Comment by AsafJosefMor** [comment]
Well, I just installed all the server and did everything from the start. Worked fine. You can close.

Thank you.

**Comment by AsafJosefMor** [comment]
OK, this is after I stopped adblocker:

![image](https://cloud.githubusercontent.com/assets/20573715/23274273/c2fdfa20-fa0a-11e6-92c4-bffd4ec0e0f9.png)
